---
name: Release
on:
  workflow_call:
    inputs:
      branch:
       type: string
       required: true
    secrets:
      token:
       required: false
      signingKey:
        required: true
      signingKeyPassword:
        required: true
      centralApiUsername:
        required: true
      centralApiPassword:
        required: true
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        required: true
        description: Which Branch to make the build from
        options:
          - main
      
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{inputs.branch}}
      - name: setup java
        uses: actions/setup-java@v4.7.1
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Set version
        run: echo "VERSION=${{inputs.branch}}" >> $GITHUB_ENV
      - name: show version
        run: echo ${VERSION}
      - name: Push to central
        run: |
          ./gradlew publishAllToNewMavenCentralApi --info \
             -Psign=true \
             -PautomaticPublish=true \
             -PversionOverride=$VERSION \
             -PsigningKeyPassword="${{ secrets.signingKeyPassword != null && secrets.signingKeyPassword || secrets.SIGNING_KEY_PASSWORD }}" \
             -PcentralApiUsername=${{ secrets.centralApiUsername != null && secrets.centralApiUsername || secrets.MAVEN_CENTRAL_USER }} \
             -PcentralApiPassword=${{ secrets.centralApiPassword != null && secrets.centralApiPassword || secrets.MAVEN_CENTRAL_PASSWORD }} \
             -PsigningKey="${{ secrets.signingKey != null && secrets.signingKey || secrets.SIGNING_KEY }}"